name: rake
description: A basic implementation of RAKE (Rapid Automatic Keyword Extraction.
version: 1.0.1
homepage: https://github.com/mathisgerdes/dart-rake

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies: 
  test: ^1.19.5
